# Generated by Django 3.2 on 2021-06-02 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bok',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='abook', to='books.book'),
        ),
    ]
