# Generated by Django 3.2 on 2021-04-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210418_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
