# Generated by Django 3.2 on 2021-06-02 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_bok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bok',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to='books.book'),
        ),
        migrations.DeleteModel(
            name='BookDetails',
        ),
    ]
