# Generated by Django 3.2 on 2021-06-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_bok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='books.category'),
        ),
    ]
